{%- set modname = "mediagrains" -%}
{%- import 'static-commontooling/docker/Dockerfile_multi_macros.j2' as macros -%}

{{ macros.preamble() }}

{{ macros.layer(modname, entrypoint=False) }}

{{ macros.testdeps(modname) }}

{{ macros.tests(modname) }}

###############################################################################
# Stage: unittest
###############################################################################
FROM tests AS unittest
WORKDIR /{{ modname }}/

COPY tests/audio.aac tests/

# Set the default command
ENTRYPOINT ["python", "-m", "unittest"]
CMD ["discover", "tests", "-v"]

{{ macros.flake8(modname) }}

{{ macros.mypy(modname) }}

{{ macros.wheel(modname) }}

{{ macros.docs(modname) }}
CMD ["--html", "--force", "--skip-errors", "--output-dir", ".", "{{ modname }}"]

FROM {{ modname + ":" + "${BUILD_TAG}" }} AS tools_base
WORKDIR /data

FROM tools_base as extract_gsf_essence
ENTRYPOINT ["extract_gsf_essence"]

FROM tools_base AS gsf_probe
ENTRYPOINT ["gsf_probe"]

FROM tools_base AS wrap_audio_in_gsf
ENTRYPOINT ["wrap_audio_in_gsf"]

FROM tools_base AS wrap_video_in_gsf
ENTRYPOINT ["wrap_video_in_gsf"]
