{%- import 'static-commontooling/docker/Dockerfile_multi_macros.j2' as macros with context -%}

{{ macros.preamble() }}

{{ macros.source() }}

{{ macros.layer(entrypoint=False) }}
CMD [ "echo", "Run one of these commands: gsf_probe extract_gsf_essence wrap_audio_in_gsf wrap_video_in_gsf" ]

{{ macros.testdeps() }}

{{ macros.tests() }}

###############################################################################
# Stage: unittest
###############################################################################
FROM tests AS unittest
WORKDIR /{{ modname }}/

COPY tests/audio.aac tests/

# Set the default command
ENTRYPOINT ["python", "-m", "unittest"]
CMD ["discover", "tests", "-v"]

{{ macros.flake8() }}

{{ macros.mypy() }}

{{ macros.wheel() }}

{{ macros.docs(with_template=True, extra_submodules=[
          "comparison", "grains", "numpy.numpy_grains", "patterngenerators", "patterngenerators.audio",
          "patterngenerators.video" , "tools", "utils"
     ])
}}
