{% macro preamble() -%}
# syntax=docker/dockerfile:1

# Args needed for base images
ARG BUILD_TAG
ARG CLOUDFIT_BASE_NAME=ap-docker.artifactory.labs.bbc/cloudfit/cloudfit_base
ARG CLOUDFIT_BASE_LABEL=latest
{%- endmacro %}

{% macro includeapilayer(apimodname) -%}
###############################################################################
# Stage: api - Alias for api specification layer
###############################################################################
FROM {{ apimodname }}:${BUILD_TAG} as api
{%- endmacro %}


{% macro source(base_image="${CLOUDFIT_BASE_NAME}:${CLOUDFIT_BASE_LABEL}") -%}
###############################################################################
# Stage: source - Builds python sdist source package for layer
###############################################################################
FROM ${CLOUDFIT_BASE_NAME}:${CLOUDFIT_BASE_LABEL} AS source
WORKDIR /{{ modname }}/

{% if with_api %}
COPY --from=api /api ./{{ modname }}/apidocs
{% endif -%}
COPY . .

RUN python3 setup.py sdist
{%- endmacro %}


{% macro layer(base_image="${CLOUDFIT_BASE_NAME}:${CLOUDFIT_BASE_LABEL}", entrypoint=True, extra_requirements_file="", install_target=None, extra_commands=[]) -%}
###############################################################################
# Stage: layer - Has layer package and its requirements installed
###############################################################################
FROM {{ base_image }} AS layer
WORKDIR /{{ modname }}/

{% for command in extra_commands -%}
{{ command }}
{% endfor -%}

# Copy in wheels if provided
COPY wheels/ ./wheels

# Install requirements
COPY requirements.txt ./
{%   if extra_requirements_file != "" -%}
COPY {{ extra_requirements_file }} ./
RUN cat {{ extra_requirements_file }} >> ./requirements.txt
{%-  endif %}

{% if install_target != None -%}
RUN --mount=type=cache,target=/root/.cache/pip --mount=type=secret,id=forgecert mkdir -p {{ install_target }} && pip install -f ./wheels -r requirements.txt -t {{ install_target }}

# Copy in everything else and install the package
ARG VERSION
COPY --from=source /{{ modname }}/dist/{{ modname }}-${VERSION}.tar.gz ./
RUN --mount=type=cache,target=/root/.cache/pip --mount=type=secret,id=forgecert tar -xvzp --strip-components=1 -f ./{{ modname }}-${VERSION}.tar.gz && cp -r ./{{ modname }} {{ install_target }}

ENV PYTHONPATH={{ install_target }}
{% else -%}
RUN --mount=type=cache,target=/root/.cache/pip --mount=type=secret,id=forgecert pip install -f ./wheels -r requirements.txt

# Copy in everything else and install the package
ARG VERSION
COPY --from=source /{{ modname }}/dist/{{ modname }}-${VERSION}.tar.gz ./
RUN --mount=type=cache,target=/root/.cache/pip --mount=type=secret,id=forgecert tar -xvzp --strip-components=1 -f ./{{ modname }}-${VERSION}.tar.gz && pip install -f ./wheels -e .
{%-  endif %}

# Set the default command
{%   if entrypoint -%}
ENTRYPOINT ["{{ modname }}"]
{%-  else -%}
ENTRYPOINT []
{%-  endif %}
{%- endmacro %}


{% macro zip(workdir="/lambda") -%}
###############################################################################
# Stage: zip
###############################################################################
FROM layer AS zip
WORKDIR {{ workdir }}

RUN yum -y install zip

ENTRYPOINT ["zip", "-r", "-", "."]
{%- endmacro %}

{% macro testdeps() -%}
###############################################################################
# Stage: testdeps - Has test dependencies installed only
###############################################################################
FROM ${CLOUDFIT_BASE_NAME}:${CLOUDFIT_BASE_LABEL} AS testdeps
WORKDIR /testdeps/

# Copy in wheels if provided
COPY wheels/ ./wheels

# Install test requirements
COPY constraints.txt ./
COPY test-requirements.txt ./
RUN --mount=type=cache,target=/root/.cache/pip --mount=type=secret,id=forgecert python -m pip install -f ./wheels --user -c constraints.txt -r ./test-requirements.txt flake8 "mypy>=0.910"
{%- endmacro %}

{% macro tests(include_extra_layers=[]) -%}
###############################################################################
# Stage: tests - Combines Layer with test dependencies
###############################################################################
FROM layer AS tests
WORKDIR /{{ modname }}/

# Install test dependencies
COPY --from=testdeps /root/.local/lib/ /root/.local/lib/

{% for layer in include_extra_layers -%}
# Copy the dependencies from the {{ layer }} layer
COPY --from={{ layer }} /root/.local/lib/ /root/.local/lib/
{% endfor -%}

ENTRYPOINT []
{%- endmacro %}

{% macro unittest() -%}
###############################################################################
# Stage: unittest - Runs unittests
###############################################################################
FROM tests AS unittest
WORKDIR /{{ modname }}/

# Set the default command
ENTRYPOINT ["python", "-m", "unittest"]
CMD ["-v"]
{%- endmacro %}

{% macro flake8() -%}
###############################################################################
# Stage: flake8 - Runs flake8 linter
###############################################################################
FROM tests AS flake8
WORKDIR /{{ modname }}/

# Copy in .flake8
COPY .flake8 ./

# Set the default command
ENTRYPOINT ["python", "-m", "flake8"]
CMD ["{{ modname }}", "tests"]
{%- endmacro %}

{% macro mypy() -%}
###############################################################################
# Stage: mypy - Runs mypy type-checker
###############################################################################
FROM tests AS mypy
WORKDIR /{{ modname }}/

# Copy in .mypy.ini
COPY .mypy.ini ./

# Create mypy cache dir. If this is missing, it can mask some errors
RUN mkdir .mypy_cache

# Set the default command
ENTRYPOINT ["python", "-m", "mypy", "--install-types", "--non-interactive"]
CMD ["--show-error-codes", "-p", "{{ modname }}"]
{%- endmacro %}

{% macro wheel() -%}
###############################################################################
# Stage: wheel - Generates sdist and wheel packages for distribution
###############################################################################
FROM layer AS wheel
WORKDIR /{{ modname }}/

COPY .tmp/_full_version.py ./{{ modname }}/_version.py
RUN pip install -f ./wheels -e .
COPY .tmp/run_with_dir_modes.sh /
RUN chmod u+x /run_with_dir_modes.sh
ENTRYPOINT ["/run_with_dir_modes.sh", "./dist", "python", "./setup.py", "sdist", "bdist_wheel"]
{%- endmacro %}

{% macro docs(with_template=False, extra_submodules=[]) -%}
###############################################################################
# Stage: docs - Generates documentation from docstrings
###############################################################################
FROM wheel AS docs
WORKDIR /docs/

# Copy the pdoc template file to the module directory
{%   if with_template -%}
COPY --from=source /{{ modname }}/module.html.jinja2 /{{ modname }}/
{%-  endif %}

RUN --mount=type=cache,target=/root/.cache/pip --mount=type=secret,id=forgecert pip install pdoc

ENTRYPOINT ["/run_with_dir_modes.sh", ".", "pdoc"]
CMD [ \
    "--output-directory", "{{ modname }}", \
{%- if with_template %}
    "--template-dir", "/{{ modname }}", \
{%- endif %}
    "{{ modname }}"{{ "," if extra_submodules }} \
{%- for extra_submodule in extra_submodules %}
    "{{ modname }}.{{ extra_submodule }}"{{ "," if not loop.last }} \
{%- endfor %}
]
{%- endmacro %}

{% macro alembic() -%}
###############################################################################
# Stage: alembic - The alembic DB migration tool configured for this layer
###############################################################################
FROM ap-docker.artifactory.labs.bbc/cloudfit/alembic:latest as alembic_base

FROM layer AS alembic

WORKDIR /data
RUN chmod a+w /data

COPY --from=alembic_base /data/requirements.txt /data/alembic.ini.j2 /data/default_entrypoint.sh .

RUN --mount=type=cache,target=/root/.cache/pip --mount=type=secret,id=forgecert pip install -r requirements.txt

ENTRYPOINT ["./default_entrypoint.sh"]
{%- endmacro %}
